ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  "Ingolf Steinhardt <info@e-spin.de>":
    - "Ingolf Steinhardt <git@e-spin.de>"
    - "e-spin <gitlab@e-spin.de>"
