services:
    metamodels.attribute_translatedfile.event_listener.build_data_definition:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\BuildDataDefinitionListener
        tags:
            -   name: kernel.event_listener
                event: dc-general.factory.build-data-definition
                method: buildDataDefinition
                priority: 0

    metamodels.attribute_translatedfile.event_listener.build_attribute:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\BuildAttributeListener
        tags:
            -   name: kernel.event_listener
                event: metamodels.dc-general.events.metamodel.build.attribute
                method: buildAttribute

    metamodels.attribute_translatedfile.event_listener.image_size_options:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\ImageSizeOptionsProvider
        arguments:
            $imageSizes: '@contao.image.sizes'
            $translator: '@translator'

    metamodels.attribute_translatedfile.event_listener.remove_type_options:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\DcGeneral\Table\Attribute\RemoveTypeOptions
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: removeOption
                priority: -1

    metamodels.attribute_translatedfile.event_listener.remove_att_id_options:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\DcGeneral\Table\FilterSetting\RemoveAttIdOptions
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: removeOption
                priority: -1

    MetaModels\AttributeTranslatedFileBundle\EventListener\DcGeneral\Table\DcaSetting\FileWidgetModeOptions:
      public: false
      arguments:
        $scopeDeterminator: '@cca.dc-general.scope-matcher'
        $factory: '@MetaModels\IFactory'
        $connection: '@database_connection'
      tags:
        - name: kernel.event_listener
          event: dc-general.view.contao2backend.get-property-options

    MetaModels\AttributeTranslatedFileBundle\EventListener\DcGeneral\Table\RenderSetting\FileImageSizeOptions:
      public: false
      arguments:
        $scopeDeterminator: '@cca.dc-general.scope-matcher'
        $factory: '@MetaModels\IFactory'
        $connection: '@database_connection'
        $optionsProvider: '@metamodels.attribute_translatedfile.event_listener.image_size_options'
      tags:
        - name: kernel.event_listener
          event: dc-general.view.contao2backend.get-property-options
